### ISSUE TITLE
你的retinanet网络可以分享一下吗

### ISSUE THREAD

**Issue by ts19970816** [Dewey1994/libtorch_retinanet#1]

**Comment by deweyamer** [comment]
我的网络是这个

https://github.com/yhenon/pytorch-retinanet

**Comment by ts19970816** [comment]
大佬，我看你知乎上的帖子，你成功的实现了libtorch部署RetinaNet网络吗？其中有些细节可以交流一下吗？我最近也在搞这个，遇到了一些问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dewey1994/libtorch_retinanet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 中午1:44
收件人:&nbsp;"Dewey1994/libtorch_retinanet"<libtorch_retinanet@noreply.github.com&gt;;
抄送:&nbsp;"1711846941"<1711846941@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Dewey1994/libtorch_retinanet] 你的retinanet网络可以分享一下吗 (#1)





 
我的网络是这个
 
https://github.com/yhenon/pytorch-retinanet

**Comment by deweyamer** [comment]
@ts19970816 好的，没问题，你知乎私我一下
