### ISSUE TITLE
torchscript

### ISSUE THREAD

**Issue by lijingle-coder** [Dewey1994/libtorch_retinanet#2]
请问下你是怎么将训练好的模型转化为pt文件的

**Comment by deweyamer** [comment]
可以参考https://pytorch.org/tutorials/advanced/cpp_export.html
里面有demo

**Comment by lijingle-coder** [comment]
@Dewey1994 你好，我这边转化pt正常，但是在编译好程序，运行时会显示error loading the model
`terminate called after throwing an instance of 'c10::Error'
  what():  open file failed, file path: /home/a/work/opencv/libtorch_retinanet-master/build/class.pt
Exception raised from FileAdapter at ../caffe2/serialize/file_adapter.cc:11 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f20ef09fb29 in /home/a/work/opencv/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd2 (0x7f20ef09cab2 in /home/a/work/opencv/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::FileAdapter::FileAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x25f (0x7f20de092aff in /home/a/work/opencv/libtorch/lib/libtorch_cpu.so)
frame #3: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x40 (0x7f20df686a00 in /home/a/work/opencv/libtorch/lib/libtorch_cpu.so)
frame #4: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>) + 0x6f (0x7f20df686b8f in /home/a/work/opencv/libtorch/lib/libtorch_cpu.so)`

报如上错误，请问下你出现这种情况了吗，我使用libtorch1.8，torchvision0.9，还有libtorch1.5，torchvision0.6都不行，

**Comment by deweyamer** [comment]
你检查一下代码 cpu gpu要对应好
要不就重新转模型
最好按着我的版本走
其他版本不保证成功= =。
